/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrayList: typeof import('./src/components/ArrayList.vue')['default']
    Child: typeof import('./src/components/Child.vue')['default']
    ClassDemo: typeof import('./src/components/ClassDemo.vue')['default']
    ComA: typeof import('./src/components/ComA.vue')['default']
    ComB: typeof import('./src/components/ComB.vue')['default']
    ComputeDemo: typeof import('./src/components/ComputeDemo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    ModelDemo: typeof import('./src/components/ModelDemo.vue')['default']
    MyCompoent: typeof import('./src/components/MyCompoent.vue')['default']
    Parent: typeof import('./src/components/Parent.vue')['default']
    RefDemo: typeof import('./src/components/RefDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/SearchComponent.vue')['default']
    StyleDemo: typeof import('./src/components/StyleDemo.vue')['default']
    WatchDemo: typeof import('./src/components/WatchDemo.vue')['default']
  }
}
